# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vlad Kap
email: vkapitoshka@gmail.com
description:  Пробная версия Блога по Администрированию и програмированию
baseurl: "/VVK"
#baseurl: "/jekyll-wing-template"
url: "http://VVK.com" # the base hostname & protocol for your site
twitter_username: vkapitoshka
github_username:  vkapitoshka

# Build settings
markdown: kramdown
